# Generated by Django 3.2.18 on 2023-04-17 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0002_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete']},
        ),
    ]
